#!/usr/bin/env ruby
site 'http://community.opscode.com/api/v1'

cookbook 'java'
cookbook 'runit'
cookbook 'ruby_build',
  :git => 'git@github.com:fnichol/chef-ruby_build.git'
cookbook 'rbenv',
  :git => 'git@github.com:fnichol/chef-rbenv.git'
cookbook 'riemann',
  :path => './'

